-- MBL Catering — rebuild items for the 36 recipes still missing grams
-- (dish name matches the dataset; some ingredient-line names differed). Rebuilds
-- each recipe.items from the dataset with correct grams, re-linking ingredient_id
-- by name against your ingredients table. Only touches these named recipes.
with seed_items(recipe_name,ord,name_en,name_zh,grams) as (
values
  ('bacon wrapped meatloves',1,'Ground beef, 90% lean 10% fat','牛絞肉(90%瘦肉,10%油脂)',180),
  ('bacon wrapped meatloves',2,'bacon','培根',20),
  ('bacon wrapped meatloves',3,'eggs','雞蛋',10),
  ('bacon wrapped meatloves',4,'green peas','青豆',10),
  ('bacon wrapped meatloves',5,'pizza mozzarella shredded','莫扎瑞拉乳酪絲',5),
  ('bacon wrapped meatloves',6,'black pepper','黑胡椒',2),
  ('bacon wrapped meatloves',7,'salt','鹽',1),
  ('beef & mint moussaka',1,'Ground beef, 90% lean 10% fat','牛絞肉(90%瘦肉,10%油脂)',220),
  ('beef & mint moussaka',2,'carrots','胡蘿蔔',5),
  ('beef & mint moussaka',3,'onions','洋蔥',50),
  ('beef & mint moussaka',4,'white wine vino de pasa','白酒',50),
  ('beef & mint moussaka',5,'eggplants','茄子',50),
  ('beef & mint moussaka',6,'milk','牛奶',100),
  ('beef & mint moussaka',7,'butter','奶油',5),
  ('beef & mint moussaka',8,'pizza mozzarella shredded','莫扎瑞拉乳酪絲',50),
  ('beef & mint moussaka',9,'black pepper','黑胡椒',2),
  ('beef & mint moussaka',10,'salt','鹽',1),
  ('beef & spinach lasagnas',1,'Ground beef, 90% lean 10% fat','牛絞肉(90%瘦肉,10%油脂)',220),
  ('beef & spinach lasagnas',2,'frozen spinach','冷凍菠菜',50),
  ('beef & spinach lasagnas',3,'pizza mozzarella shredded','莫扎瑞拉乳酪絲',50),
  ('beef & spinach lasagnas',4,'milk','牛奶',50),
  ('beef & spinach lasagnas',5,'butter','奶油',10),
  ('beef & spinach lasagnas',6,'tomato sauce','蕃茄泥',50),
  ('beef & spinach lasagnas',7,'black pepper','黑胡椒',2),
  ('beef & spinach lasagnas',8,'salt','鹽',1),
  ('beef bolognaise',1,'Ground beef, 90% lean 10% fat','牛絞肉(90%瘦肉,10%油脂)',180),
  ('beef bolognaise',2,'carrots','胡蘿蔔',20),
  ('beef bolognaise',3,'onions','洋蔥',10),
  ('beef bolognaise',4,'tomato sauce','蕃茄泥',50),
  ('beef bolognaise',5,'olive oil (EVOO)','橄欖油 (EVOO)',5),
  ('beef bolognaise',6,'black pepper','黑胡椒',2),
  ('beef bolognaise',7,'salt','鹽',1),
  ('beef bolognaise burrito',1,'Ground beef, 90% lean 10% fat','牛絞肉(90%瘦肉,10%油脂)',220),
  ('beef bolognaise burrito',2,'onions','洋蔥',10),
  ('beef bolognaise burrito',3,'carrots','胡蘿蔔',10),
  ('beef bolognaise burrito',4,'pizza mozzarella shredded','莫扎瑞拉乳酪絲',10),
  ('beef bolognaise burrito',5,'tomato sauce','蕃茄泥',20),
  ('beef bolognaise burrito',6,'tortilla','墨西哥捲餅',15),
  ('beef bolognaise burrito',7,'black pepper','黑胡椒',2),
  ('beef bolognaise burrito',8,'salt','鹽',1),
  ('beef burger, blue cheese sauce',1,'Ground beef, 90% lean 10% fat','牛絞肉(90%瘦肉,10%油脂)',220),
  ('beef burger, blue cheese sauce',2,'eggs','雞蛋',25),
  ('beef burger, blue cheese sauce',3,'milky lux cream','鮮奶油',10),
  ('beef burger, blue cheese sauce',4,'danish blue cheese','丹麥藍紋乳酪',15),
  ('beef burger, blue cheese sauce',5,'white wine vino de pasa','白酒',10),
  ('beef burger, blue cheese sauce',6,'black pepper','黑胡椒',2),
  ('beef burger, blue cheese sauce',7,'salt','鹽',1),
  ('beef burger, chili corn carne sauce',1,'Ground beef, 90% lean 10% fat','牛絞肉(90%瘦肉,10%油脂)',180),
  ('beef burger, chili corn carne sauce',2,'red kidney beans','紅腰豆',10),
  ('beef burger, chili corn carne sauce',3,'green sweet peppers','青椒',10),
  ('beef burger, chili corn carne sauce',4,'red sweet peppers','紅色甜椒',10),
  ('beef burger, chili corn carne sauce',5,'tomato sauce','蕃茄泥',20),
  ('beef burger, chili corn carne sauce',6,'chili powder','辣椒粉',2),
  ('beef burger, chili corn carne sauce',7,'eggs','雞蛋',100),
  ('beef burger, mushroom sauce',1,'Ground beef, 90% lean 10% fat','牛絞肉(90%瘦肉,10%油脂)',220),
  ('beef burger, mushroom sauce',2,'brown beech mushrooms','鴻喜菇',20),
  ('beef burger, mushroom sauce',3,'milky lux cream','鮮奶油',20),
  ('beef burger, mushroom sauce',4,'onions','洋蔥',10),
  ('beef burger, mushroom sauce',5,'white wine vino de pasa','白酒',10),
  ('beef burger, mushroom sauce',6,'garlic','大蒜',2),
  ('beef burger, mushroom sauce',7,'black pepper','黑胡椒',2),
  ('beef burger, mushroom sauce',8,'salt','鹽',1),
  ('beef burger, scottish whisky sauce',1,'Ground beef, 90% lean 10% fat','牛絞肉(90%瘦肉,10%油脂)',220),
  ('beef burger, scottish whisky sauce',2,'milky lux cream','鮮奶油',50),
  ('beef burger, scottish whisky sauce',3,'onions','洋蔥',20),
  ('beef burger, scottish whisky sauce',4,'black pepper','黑胡椒',2),
  ('beef burger, scottish whisky sauce',5,'salt','鹽',1),
  ('beef filet grand-mere papillotte',1,'beef, loin cut','菲力牛肉',180),
  ('beef filet grand-mere papillotte',2,'onions','洋蔥',20),
  ('beef filet grand-mere papillotte',3,'bacon','培根',30),
  ('beef filet grand-mere papillotte',4,'brown beech mushrooms','鴻喜菇',20),
  ('beef filet grand-mere papillotte',5,'red wine "cabernet sauviginon"','紅酒 "Cabernet sauvignon"',20),
  ('beef filet grand-mere papillotte',6,'salt','鹽',1),
  ('beef filet, butter, garlic and parsley',1,'beef, loin cut','菲力牛肉',220),
  ('beef filet, butter, garlic and parsley',2,'butter','奶油',40),
  ('beef filet, butter, garlic and parsley',3,'garlic','大蒜',10),
  ('beef filet, butter, garlic and parsley',4,'parsley','巴西里',10),
  ('beef filet, butter, garlic and parsley',5,'black pepper','黑胡椒',2),
  ('beef filet, butter, garlic and parsley',6,'salt','鹽',1),
  ('beef friand',1,'Ground beef, 90% lean 10% fat','牛絞肉(90%瘦肉,10%油脂)',150),
  ('beef friand',2,'pork loin, boneless','豬里肌',30),
  ('beef friand',3,'puff pastry','酥皮',20),
  ('beef friand',4,'onions','洋蔥',20),
  ('beef friand',5,'black pepper','黑胡椒',2),
  ('beef friand',6,'salt','鹽',1),
  ('beef koftas',1,'Ground beef, 90% lean 10% fat','牛絞肉(90%瘦肉,10%油脂)',180),
  ('beef koftas',2,'cumin powder','孜然粉',2),
  ('beef koftas',3,'turmeric','薑黃',2),
  ('beef koftas',4,'garlic','大蒜',2),
  ('beef koftas',5,'olive oil (EVOO)','橄欖油 (EVOO)',2),
  ('beef lasagnas',1,'Ground beef, 90% lean 10% fat','牛絞肉(90%瘦肉,10%油脂)',220),
  ('beef lasagnas',2,'tomato sauce','蕃茄泥',20),
  ('beef lasagnas',3,'pizza mozzarella shredded','莫扎瑞拉乳酪絲',20),
  ('beef lasagnas',4,'lasagnas pasta','千層麵',20),
  ('beef lasagnas',5,'butter','奶油',5),
  ('beef lasagnas',6,'milk','牛奶',20),
  ('beef lasagnas',7,'onions','洋蔥',5),
  ('beef lasagnas',8,'carrots','胡蘿蔔',5),
  ('beef lasagnas',9,'corn starch','玉米粉',10),
  ('beef lasagnas',10,'black pepper','黑胡椒',2),
  ('beef lasagnas',11,'salt','鹽',1),
  ('beef meatballs & mushrooms sauce',1,'Ground beef, 90% lean 10% fat','牛絞肉(90%瘦肉,10%油脂)',220),
  ('beef meatballs & mushrooms sauce',2,'onions','洋蔥',10),
  ('beef meatballs & mushrooms sauce',3,'garlic','大蒜',5),
  ('beef meatballs & mushrooms sauce',4,'milky lux cream','鮮奶油',20),
  ('beef meatballs & mushrooms sauce',5,'brown beech mushrooms','鴻喜菇',20),
  ('beef meatballs & mushrooms sauce',6,'white wine vino de pasa','白酒',15),
  ('beef meatballs & mushrooms sauce',7,'black pepper','黑胡椒',2),
  ('beef meatballs & mushrooms sauce',8,'salt','鹽',1),
  ('beef meatballs & tomato sauce',1,'Ground beef, 90% lean 10% fat','牛絞肉(90%瘦肉,10%油脂)',220),
  ('beef meatballs & tomato sauce',2,'eggs','雞蛋',25),
  ('beef meatballs & tomato sauce',3,'tomato sauce','蕃茄泥',100),
  ('beef meatballs & tomato sauce',4,'carrots','胡蘿蔔',10),
  ('beef meatballs & tomato sauce',5,'onions','洋蔥',10),
  ('beef meatballs & tomato sauce',6,'olive oil (EVOO)','橄欖油 (EVOO)',5),
  ('beef meatballs & tomato sauce',7,'thyme','百里香',2),
  ('beef meatballs & tomato sauce',8,'black pepper','黑胡椒',2),
  ('beef meatballs & tomato sauce',9,'salt','鹽',1),
  ('beef meatballs, green olives & mozarella cheese sauce',1,'Ground beef, 90% lean 10% fat','牛絞肉(90%瘦肉,10%油脂)',180),
  ('beef meatballs, green olives & mozarella cheese sauce',2,'onions','洋蔥',10),
  ('beef meatballs, green olives & mozarella cheese sauce',3,'black olives','黑橄欖',10),
  ('beef meatballs, green olives & mozarella cheese sauce',4,'pizza mozzarella shredded','莫扎瑞拉乳酪絲',20),
  ('beef meatballs, green olives & mozarella cheese sauce',5,'white wine vino de pasa','白酒',10),
  ('beef meatballs, green olives & mozarella cheese sauce',6,'salt','鹽',1),
  ('beef meatballs, green olives & mozarella cheese sauce',7,'salt','鹽',0),
  ('beef meatballs, tofu & sechuan pepper',1,'Ground beef, 90% lean 10% fat','牛絞肉(90%瘦肉,10%油脂)',180),
  ('beef meatballs, tofu & sechuan pepper',2,'tofu','豆乾',30),
  ('beef meatballs, tofu & sechuan pepper',3,'schezuan pepper','花椒',5),
  ('beef meatballs, tofu & sechuan pepper',4,'soy sauce (5L)','醬油 (5L)',5),
  ('beef meatballs, tofu & sechuan pepper',5,'butter','奶油',5),
  ('beef meatballs, tofu & sechuan pepper',6,'tomato sauce','蕃茄泥',20),
  ('beef meatballs, tofu & sechuan pepper',7,'black pepper','黑胡椒',2),
  ('beef meatballs, tofu & sechuan pepper',8,'salt','鹽',1),
  ('braised beef, red wine sauce',1,'beef, loin cut','菲力牛肉',220),
  ('braised beef, red wine sauce',2,'red wine "cabernet sauviginon"','紅酒 "Cabernet sauvignon"',20),
  ('braised beef, red wine sauce',3,'onions','洋蔥',10),
  ('braised beef, red wine sauce',4,'bacon','培根',10),
  ('braised beef, red wine sauce',5,'olive oil (EVOO)','橄欖油 (EVOO)',5),
  ('braised beef, red wine sauce',6,'corn starch','玉米粉',5),
  ('braised beef, red wine sauce',7,'black pepper','黑胡椒',2),
  ('braised beef, red wine sauce',8,'salt','鹽',1),
  ('braised slice filet beef, tomato',1,'beef, loin cut','菲力牛肉',220),
  ('braised slice filet beef, tomato',2,'onions','洋蔥',10),
  ('braised slice filet beef, tomato',3,'tomato sauce','蕃茄泥',20),
  ('braised slice filet beef, tomato',4,'carrots','胡蘿蔔',10),
  ('braised slice filet beef, tomato',5,'garlic','大蒜',50),
  ('braised slice filet beef, tomato',6,'black pepper','黑胡椒',2),
  ('braised slice filet beef, tomato',7,'salt','鹽',1),
  ('cabbage stuffed with meat',1,'Ground beef, 90% lean 10% fat','牛絞肉(90%瘦肉,10%油脂)',160),
  ('cabbage stuffed with meat',2,'ground pork','豬絞肉',60),
  ('cabbage stuffed with meat',3,'green cabbage','綠色高麗菜',20),
  ('cabbage stuffed with meat',4,'white wine vino de pasa','白酒',5),
  ('cabbage stuffed with meat',5,'milky lux cream','鮮奶油',5),
  ('cabbage stuffed with meat',6,'salt','鹽',1),
  ('cabbage stuffed with meat',7,'black pepper','黑胡椒',2),
  ('chili con carne',1,'Ground beef, 90% lean 10% fat','牛絞肉(90%瘦肉,10%油脂)',220),
  ('chili con carne',2,'tomato sauce','蕃茄泥',50),
  ('chili con carne',3,'chili powder','辣椒粉',2),
  ('chili con carne',4,'cumin powder','孜然粉',2),
  ('chili con carne',5,'olive oil (EVOO)','橄欖油 (EVOO)',5),
  ('chili con carne',6,'red kidney beans','紅腰豆',20),
  ('chili con carne',7,'black pepper','黑胡椒',2),
  ('chili con carne',8,'salt','鹽',1),
  ('chili con carne w/ filet beef',1,'beef, loin cut','菲力牛肉',220),
  ('chili con carne w/ filet beef',2,'sweet corn','玉米罐',20),
  ('chili con carne w/ filet beef',3,'chili powder','辣椒粉',5),
  ('chili con carne w/ filet beef',4,'red kidney beans','紅腰豆',40),
  ('chili con carne w/ filet beef',5,'cumin powder','孜然粉',5),
  ('chili con carne w/ filet beef',6,'onions','洋蔥',10),
  ('chili con carne w/ filet beef',7,'black pepper','黑胡椒',2),
  ('chili con carne w/ filet beef',8,'salt','鹽',1),
  ('filet beef wellington, red wine sauce',1,'beef, loin cut','菲力牛肉',180),
  ('filet beef wellington, red wine sauce',2,'brown beech mushrooms','鴻喜菇',40),
  ('filet beef wellington, red wine sauce',3,'puff pastry','酥皮',20),
  ('filet beef wellington, red wine sauce',4,'serrano ham','塞蘭諾火腿',30),
  ('filet beef wellington, red wine sauce',5,'eggs','雞蛋',100),
  ('filet beef wellington, red wine sauce',6,'black pepper','黑胡椒',2),
  ('filet beef wellington, red wine sauce',7,'salt','鹽',1),
  ('filet beef, and original aioli sauce',1,'beef, loin cut','菲力牛肉',180),
  ('filet beef, and original aioli sauce',2,'olive oil (EVOO)','橄欖油 (EVOO)',5),
  ('filet beef, and original aioli sauce',3,'eggs','雞蛋',50),
  ('filet beef, and original aioli sauce',4,'garlic','大蒜',2),
  ('filet beef, and original aioli sauce',5,'onions','洋蔥',2),
  ('filet beef, and original aioli sauce',6,'black pepper','黑胡椒',2),
  ('filet beef, and original aioli sauce',7,'salt','鹽',1),
  ('grilled filet beef & gravy sauce',1,'beef, loin cut','菲力牛肉',180),
  ('grilled filet beef & gravy sauce',2,'onions','洋蔥',5),
  ('grilled filet beef & gravy sauce',3,'garlic','大蒜',2),
  ('roast beef, black pepper sauce',1,'beef, loin cut','菲力牛肉',220),
  ('roast beef, black pepper sauce',2,'black pepper','黑胡椒',5),
  ('roast beef, black pepper sauce',3,'white wine vino de pasa','白酒',10),
  ('roast beef, black pepper sauce',4,'milky lux cream','鮮奶油',5),
  ('roast beef, black pepper sauce',5,'salt','鹽',5),
  ('roast beef, black pepper sauce',6,'brown beech mushrooms','鴻喜菇',10),
  ('roast beef, black pepper sauce',7,'olive oil (EVOO)','橄欖油 (EVOO)',5),
  ('roast beef, blue cheese sauce',1,'beef, loin cut','菲力牛肉',180),
  ('roast beef, blue cheese sauce',2,'danish blue cheese','丹麥藍紋乳酪',10),
  ('roast beef, blue cheese sauce',3,'onions','洋蔥',5),
  ('roast beef, blue cheese sauce',4,'white wine vino de pasa','白酒',10),
  ('roast beef, blue cheese sauce',5,'corn starch','玉米粉',5),
  ('roast beef, blue cheese sauce',6,'olive oil (EVOO)','橄欖油 (EVOO)',5),
  ('roast beef, blue cheese sauce',7,'black pepper','黑胡椒',2),
  ('roast beef, blue cheese sauce',8,'salt','鹽',1),
  ('roast beef, chasseur sauce',1,'beef, loin cut','菲力牛肉',180),
  ('roast beef, chasseur sauce',2,'tomato sauce','蕃茄泥',50),
  ('roast beef, chasseur sauce',3,'onions','洋蔥',10),
  ('roast beef, chasseur sauce',4,'white wine vino de pasa','白酒',10),
  ('roast beef, chasseur sauce',5,'corn starch','玉米粉',5),
  ('roast beef, chasseur sauce',6,'olive oil (EVOO)','橄欖油 (EVOO)',5),
  ('roast beef, chasseur sauce',7,'black pepper','黑胡椒',2),
  ('roast beef, chasseur sauce',8,'salt','鹽',1),
  ('roast beef, jalapenos sauce',1,'beef, loin cut','菲力牛肉',220),
  ('roast beef, jalapenos sauce',2,'onions','洋蔥',10),
  ('roast beef, jalapenos sauce',3,'white wine vino de pasa','白酒',10),
  ('roast beef, jalapenos sauce',4,'milky lux cream','鮮奶油',5),
  ('roast beef, jalapenos sauce',5,'black pepper','黑胡椒',2),
  ('roast beef, jalapenos sauce',6,'salt','鹽',1),
  ('roast beef, mushroms duxelles & ginger',1,'beef, loin cut','菲力牛肉',180),
  ('roast beef, mushroms duxelles & ginger',2,'king oyster mushrooms','杏鮑菇',20),
  ('roast beef, mushroms duxelles & ginger',3,'ginger','薑',2),
  ('roast beef, mushroms duxelles & ginger',4,'olive oil (EVOO)','橄欖油 (EVOO)',2),
  ('roast beef, mushroms duxelles & ginger',5,'butter','奶油',5),
  ('roast beef, mushroom sauce',1,'beef, loin cut','菲力牛肉',220),
  ('roast beef, mushroom sauce',2,'Sunflower oil','葵花油(3L)',10),
  ('roast beef, mushroom sauce',3,'white wine vino de pasa','白酒',10),
  ('roast beef, mushroom sauce',4,'brown beech mushrooms','鴻喜菇',10),
  ('roast beef, mushroom sauce',5,'milky lux cream','鮮奶油',5),
  ('roast beef, mushroom sauce',6,'olive oil (EVOO)','橄欖油 (EVOO)',2),
  ('roast beef, mushroom sauce',7,'black pepper','黑胡椒',2),
  ('roast beef, mushroom sauce',8,'salt','鹽',1),
  ('roast beef, mushrooms duxelles & ginger',1,'beef, loin cut','菲力牛肉',220),
  ('roast beef, mushrooms duxelles & ginger',2,'olive oil (EVOO)','橄欖油 (EVOO)',5),
  ('roast beef, mushrooms duxelles & ginger',3,'milky lux cream','鮮奶油',20),
  ('roast beef, mushrooms duxelles & ginger',4,'white wine vino de pasa','白酒',20),
  ('roast beef, mushrooms duxelles & ginger',5,'brown beech mushrooms','鴻喜菇',20),
  ('roast beef, mushrooms duxelles & ginger',6,'ginger','薑',5),
  ('roast beef, mushrooms duxelles & ginger',7,'black pepper','黑胡椒',2),
  ('roast beef, mushrooms duxelles & ginger',8,'salt','鹽',1),
  ('roast beef, onion sauce',1,'beef, loin cut','菲力牛肉',220),
  ('roast beef, onion sauce',2,'olive oil (EVOO)','橄欖油 (EVOO)',5),
  ('roast beef, onion sauce',3,'onions','洋蔥',10),
  ('roast beef, onion sauce',4,'white wine vino de pasa','白酒',20),
  ('roast beef, onion sauce',5,'garlic','大蒜',50),
  ('roast beef, onion sauce',6,'corn starch','玉米粉',5),
  ('roast beef, onion sauce',7,'black pepper','黑胡椒',2),
  ('roast beef, onion sauce',8,'salt','鹽',1),
  ('roast beef, parmesan sauce',1,'beef, loin cut','菲力牛肉',200),
  ('roast beef, parmesan sauce',2,'milky lux cream','鮮奶油',5),
  ('roast beef, parmesan sauce',3,'anchor parmesan cheese','安佳帕瑪森起司',5),
  ('roast beef, parmesan sauce',4,'onions','洋蔥',2),
  ('roast beef, parmesan sauce',5,'Sunflower oil','葵花油(3L)',2),
  ('roast beef, parmesan sauce',6,'black pepper','黑胡椒',2),
  ('roast beef, parmesan sauce',7,'salt','鹽',1),
  ('steak au poivre, (beef pepper with cognac)',1,'beef, loin cut','菲力牛肉',200),
  ('steak au poivre, (beef pepper with cognac)',2,'onions','洋蔥',10),
  ('steak au poivre, (beef pepper with cognac)',3,'garlic','大蒜',5),
  ('steak au poivre, (beef pepper with cognac)',4,'milky lux cream','鮮奶油',20),
  ('steak au poivre, (beef pepper with cognac)',5,'black pepper','黑胡椒',8),
  ('steak au poivre, (beef pepper with cognac)',6,'salt','鹽',1)
),
resolved as (
  select si.recipe_name, si.ord,
         jsonb_build_object(
           'name_en', si.name_en,
           'name_zh', coalesce(ing.name_zh, si.name_zh),
           'ingredient_id', ing.id,
           'grams', si.grams
         ) as elem
  from seed_items si
  left join public.ingredients ing on lower(trim(ing.name_en)) = lower(trim(si.name_en))
),
built as (
  select recipe_name, jsonb_agg(elem order by ord) as items
  from resolved group by recipe_name
)
update public.recipes r set items = built.items
from built
where lower(trim(r.name_en)) = lower(trim(built.recipe_name));

select count(*) filter (where exists (select 1 from jsonb_array_elements(items) e where (e->>'grams') is null)) as recipes_still_missing_grams
from public.recipes;
